[platformio]
default_envs = seeed_xiao_esp32s3

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200
monitor_filters =
    esp32_exception_decoder
    time

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -I src/app/inc
    -I src/hal/inc
    -I src/protocol/inc
    -D RS485_UART_NUM=1
    -D RS485_TX_PIN=43
    -D RS485_RX_PIN=44
    -D RS485_DE_RE_PIN=5
    -D RS485_SCAN_ID_MIN=1
    -D RS485_SCAN_ID_MAX=10
    -D RS485_RESPONSE_TIMEOUT_MS=120
    -D RS485_POLL_INTERVAL_MS=5000
    -D RS485_RESCAN_INTERVAL_MS=10000
