M48
; DRILL file KiCad 10.0.5 date 2026-08-01T09:27:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-01T09:27:58+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X18.0Y-68.0
X22.0Y-35.0
X54.0Y-68.0
X90.0Y-68.0
X126.0Y-68.0
X162.0Y-68.0
T2
X4.0Y-4.0
X4.0Y-111.0
X176.0Y-4.0
X176.0Y-111.0
M30
