interface=wlan0
bind-dynamic
listen-address=192.168.50.1
dhcp-authoritative
dhcp-range=192.168.50.50,192.168.50.199,255.255.255.0,12h
dhcp-option=option:router,192.168.50.1
dhcp-option=option:ntp-server,192.168.50.1
domain=devices.inas
local=/devices.inas/
address=/mqtt.devices.inas/192.168.50.1
address=/setup.devices.inas/192.168.50.1
no-resolv
domain-needed
bogus-priv
