DEVICE_ID := soil-sensor-device
DEVICE_KIND := SOI
DEVICE_NAME := SOI Soil Sensor
DEVICE_VERSION := 0.1.0
PIO_ENV := seeed_xiao_esp32s3
ESP_CHIP := esp32s3
FLASH_SIZE := 8MB
HAS_FILESYSTEM := 1

include ../common/make/esp32-firmware.mk
